package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TarifaId generated by hbm2java
 */
@Embeddable
public class AsistenciaId  implements java.io.Serializable {


     private String estudianteTipoDocumento;
     private String estudianteDocumento;
     private int claseIdClase;
     private int claseGrupoCursoIdCurso;
     private int claseGrupoIdGrupo;
    AsistenciaId() {
    }

    public AsistenciaId(String estudianteTipoDocumento, String estudianteDocumento, int claseIdClase, int claseGrupoCursoIdCurso, int claseGrupoIdGrupo) {
        this.estudianteTipoDocumento = estudianteTipoDocumento;
        this.estudianteDocumento = estudianteDocumento;
        this.claseIdClase = claseIdClase;
        this.claseGrupoCursoIdCurso = claseGrupoCursoIdCurso;
        this.claseGrupoIdGrupo = claseGrupoIdGrupo;
    }
    @Column(name="Estudiante_Tipo_Documento", nullable=false, length=5)
    public String getEstudianteTipoDocumento() {
        return estudianteTipoDocumento;
    }
    
    public void setEstudianteTipoDocumento(String estudianteTipoDocumento) {
        this.estudianteTipoDocumento = estudianteTipoDocumento;
    }
    
    @Column(name="Estudiante_Documento", nullable=false, length=45)
    public String getEstudianteDocumento() {
        return estudianteDocumento;
    }

    public void setEstudianteDocumento(String estudianteDocumento) {
        this.estudianteDocumento = estudianteDocumento;
    }
    
    @Column(name="Clase_Id_Clase", nullable=false)
    public int getClaseIdClase() {
        return claseIdClase;
    }

    public void setClaseIdClase(int claseIdClase) {
        this.claseIdClase = claseIdClase;
    }

    @Column(name="Clase_Grupo_Curso_Id_Curso", nullable=false)
    public int getClaseGrupoCursoIdCurso() {
        return claseGrupoCursoIdCurso;
    }

    public void setClaseGrupoCursoIdCurso(int claseGrupoCursoIdCurso) {
        this.claseGrupoCursoIdCurso = claseGrupoCursoIdCurso;
    }

    @Column(name="Clase_Grupo_Id_Curso", nullable=false)
    public int getClaseGrupoIdGrupo() {
        return claseGrupoIdGrupo;
    }

    public void setClaseGrupoIdGrupo(int claseGrupoIdGrupo) {
        this.claseGrupoIdGrupo = claseGrupoIdGrupo;
    }


}


