package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name="Clase"
    ,catalog="mydb"
)
public class Clase  implements java.io.Serializable {


     private ClaseId id;
     private Grupo grupo;
     private String estado;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Clase() {
    }

	
    public Clase(ClaseId id, Grupo grupo, String estado) {
        this.id = id;
        this.grupo = grupo;
        this.estado = estado;
    }
    public Clase(ClaseId id, Grupo grupo, String estado, Set<Estudiante> estudiantes) {
       this.id = id;
       this.grupo = grupo;
       this.estado = estado;
       this.estudiantes = estudiantes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idClase", column=@Column(name="idClase", nullable=false) ), 
        @AttributeOverride(name="grupoCursoIdCurso", column=@Column(name="Grupo_Curso_id_Curso", nullable=false) ), 
        @AttributeOverride(name="grupoIdGrupo", column=@Column(name="Grupo_idGrupo", nullable=false) ) } )
    public ClaseId getId() {
        return this.id;
    }
    
    public void setId(ClaseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Grupo_Curso_id_Curso", referencedColumnName="Curso_id_Curso", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Grupo_idGrupo", referencedColumnName="idGrupo", nullable=false, insertable=false, updatable=false) } )
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="Estado", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Asistencia", catalog="mydb", joinColumns = { 
        @JoinColumn(name="Clase_idClase", nullable=false, updatable=false), 
        @JoinColumn(name="Clase_Grupo_Curso_id_Curso", nullable=false, updatable=false), 
        @JoinColumn(name="Clase_Grupo_idGrupo", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Estudiante_Tipo_Documento", nullable=false, updatable=false) })
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


