package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrupoId generated by hbm2java
 */
@Embeddable
public class GrupoId  implements java.io.Serializable {


     private int cursoIdCurso;
     private int idGrupo;

    public GrupoId() {
    }

    public GrupoId(int cursoIdCurso, int idGrupo) {
       this.cursoIdCurso = cursoIdCurso;
       this.idGrupo = idGrupo;
    }
   


    @Column(name="Curso_id_Curso", nullable=false)
    public int getCursoIdCurso() {
        return this.cursoIdCurso;
    }
    
    public void setCursoIdCurso(int cursoIdCurso) {
        this.cursoIdCurso = cursoIdCurso;
    }


    @Column(name="idGrupo", nullable=false)
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GrupoId) ) return false;
		 GrupoId castOther = ( GrupoId ) other; 
         
		 return (this.getCursoIdCurso()==castOther.getCursoIdCurso())
 && (this.getIdGrupo()==castOther.getIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCursoIdCurso();
         result = 37 * result + this.getIdGrupo();
         return result;
   }   


}


