package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HorarioId generated by hbm2java
 */
@Embeddable
public class HorarioId  implements java.io.Serializable {


     private String dia;
     private int grupoCursoIdCurso;
     private int grupoIdGrupo;

    public HorarioId() {
    }

    public HorarioId(String dia, int grupoCursoIdCurso, int grupoIdGrupo) {
       this.dia = dia;
       this.grupoCursoIdCurso = grupoCursoIdCurso;
       this.grupoIdGrupo = grupoIdGrupo;
    }
   


    @Column(name="Dia", nullable=false, length=10)
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }


    @Column(name="Grupo_Curso_id_Curso", nullable=false)
    public int getGrupoCursoIdCurso() {
        return this.grupoCursoIdCurso;
    }
    
    public void setGrupoCursoIdCurso(int grupoCursoIdCurso) {
        this.grupoCursoIdCurso = grupoCursoIdCurso;
    }


    @Column(name="Grupo_idGrupo", nullable=false)
    public int getGrupoIdGrupo() {
        return this.grupoIdGrupo;
    }
    
    public void setGrupoIdGrupo(int grupoIdGrupo) {
        this.grupoIdGrupo = grupoIdGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HorarioId) ) return false;
		 HorarioId castOther = ( HorarioId ) other; 
         
		 return ( (this.getDia()==castOther.getDia()) || ( this.getDia()!=null && castOther.getDia()!=null && this.getDia().equals(castOther.getDia()) ) )
 && (this.getGrupoCursoIdCurso()==castOther.getGrupoCursoIdCurso())
 && (this.getGrupoIdGrupo()==castOther.getGrupoIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDia() == null ? 0 : this.getDia().hashCode() );
         result = 37 * result + this.getGrupoCursoIdCurso();
         result = 37 * result + this.getGrupoIdGrupo();
         return result;
   }   


}


