package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="Horario"
    ,catalog="mydb"
)
public class Horario  implements java.io.Serializable {


     private HorarioId id;
     private Grupo grupo;
     private Date horaInicio;
     private Date horaFin;

    public Horario() {
    }

    public Horario(HorarioId id, Grupo grupo, Date horaInicio, Date horaFin) {
       this.id = id;
       this.grupo = grupo;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dia", column=@Column(name="Dia", nullable=false, length=10) ), 
        @AttributeOverride(name="grupoCursoIdCurso", column=@Column(name="Grupo_Curso_id_Curso", nullable=false) ), 
        @AttributeOverride(name="grupoIdGrupo", column=@Column(name="Grupo_idGrupo", nullable=false) ) } )
    public HorarioId getId() {
        return this.id;
    }
    
    public void setId(HorarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Grupo_Curso_id_Curso", referencedColumnName="Curso_id_Curso", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Grupo_idGrupo", referencedColumnName="idGrupo", nullable=false, insertable=false, updatable=false) } )
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Hora_Inicio", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Hora_Fin", nullable=false, length=8)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


