package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarifa generated by hbm2java
 */
@Entity
@Table(name="Tarifa"
    ,catalog="mydb"
)
public class Tarifa  implements java.io.Serializable {


     private TarifaId id;
     private Curso curso;
     private String tipo;
     private String valor;
     private Date fechaPago;

    public Tarifa() {
    }

	
    public Tarifa(TarifaId id, Curso curso, String tipo, String valor) {
        this.id = id;
        this.curso = curso;
        this.tipo = tipo;
        this.valor = valor;
    }
    public Tarifa(TarifaId id, Curso curso, String tipo, String valor, Date fechaPago) {
       this.id = id;
       this.curso = curso;
       this.tipo = tipo;
       this.valor = valor;
       this.fechaPago = fechaPago;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cursoIdCurso", column=@Column(name="Curso_id_Curso", nullable=false) ), 
        @AttributeOverride(name="idTarifa", column=@Column(name="idTarifa", nullable=false) ) } )
    public TarifaId getId() {
        return this.id;
    }
    
    public void setId(TarifaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Curso_id_Curso", nullable=false, insertable=false, updatable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name="Tipo", nullable=false, length=25)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="Valor", nullable=false, length=25)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Pago", length=10)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }




}


