package dto;
// Generated 28/11/2016 09:17:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TarifaId generated by hbm2java
 */
@Embeddable
public class TarifaId  implements java.io.Serializable {


     private int cursoIdCurso;
     private int idTarifa;

    public TarifaId() {
    }

    public TarifaId(int cursoIdCurso, int idTarifa) {
       this.cursoIdCurso = cursoIdCurso;
       this.idTarifa = idTarifa;
    }
   


    @Column(name="Curso_id_Curso", nullable=false)
    public int getCursoIdCurso() {
        return this.cursoIdCurso;
    }
    
    public void setCursoIdCurso(int cursoIdCurso) {
        this.cursoIdCurso = cursoIdCurso;
    }


    @Column(name="idTarifa", nullable=false)
    public int getIdTarifa() {
        return this.idTarifa;
    }
    
    public void setIdTarifa(int idTarifa) {
        this.idTarifa = idTarifa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TarifaId) ) return false;
		 TarifaId castOther = ( TarifaId ) other; 
         
		 return (this.getCursoIdCurso()==castOther.getCursoIdCurso())
 && (this.getIdTarifa()==castOther.getIdTarifa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCursoIdCurso();
         result = 37 * result + this.getIdTarifa();
         return result;
   }   


}


